layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  behance: patmyron
  # dribbble: your_username
  facebook: patmyron
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: patrickmyron
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 4122849
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://patmyron.com
  # youtube: your_username
